// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package model

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type articleTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *articleTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("News").
func (v *articleTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *articleTableType) Columns() []string {
	return []string{
		"id",
		"title",
		"content",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *articleTableType) NewStruct() reform.Struct {
	return new(Article)
}

// NewRecord makes a new record for that table.
func (v *articleTableType) NewRecord() reform.Record {
	return new(Article)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *articleTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// ArticleTable represents News view or table in SQL database.
var ArticleTable = &articleTableType{
	s: parse.StructInfo{
		Type:    "Article",
		SQLName: "News",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int32", Column: "id"},
			{Name: "Title", Type: "string", Column: "title"},
			{Name: "Content", Type: "string", Column: "content"},
		},
		PKFieldIndex: 0,
	},
	z: new(Article).Values(),
}

// String returns a string representation of this struct or record.
func (s Article) String() string {
	res := make([]string, 3)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Title: " + reform.Inspect(s.Title, true)
	res[2] = "Content: " + reform.Inspect(s.Content, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Article) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Title,
		s.Content,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Article) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Title,
		&s.Content,
	}
}

// View returns View object for that struct.
func (s *Article) View() reform.View {
	return ArticleTable
}

// Table returns Table object for that record.
func (s *Article) Table() reform.Table {
	return ArticleTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Article) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Article) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Article) HasPK() bool {
	return s.ID != ArticleTable.z[ArticleTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *Article) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = ArticleTable
	_ reform.Struct = (*Article)(nil)
	_ reform.Table  = ArticleTable
	_ reform.Record = (*Article)(nil)
	_ fmt.Stringer  = (*Article)(nil)
)

type categoryViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *categoryViewType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("NewsCategories").
func (v *categoryViewType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *categoryViewType) Columns() []string {
	return []string{
		"NewsId",
		"CategoryId",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *categoryViewType) NewStruct() reform.Struct {
	return new(Category)
}

// CategoryView represents NewsCategories view or table in SQL database.
var CategoryView = &categoryViewType{
	s: parse.StructInfo{
		Type:    "Category",
		SQLName: "NewsCategories",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int32", Column: "NewsId"},
			{Name: "CatID", Type: "int32", Column: "CategoryId"},
		},
		PKFieldIndex: -1,
	},
	z: new(Category).Values(),
}

// String returns a string representation of this struct or record.
func (s Category) String() string {
	res := make([]string, 2)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "CatID: " + reform.Inspect(s.CatID, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Category) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.CatID,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Category) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.CatID,
	}
}

// View returns View object for that struct.
func (s *Category) View() reform.View {
	return CategoryView
}

// check interfaces
var (
	_ reform.View   = CategoryView
	_ reform.Struct = (*Category)(nil)
	_ fmt.Stringer  = (*Category)(nil)
)

func init() {
	parse.AssertUpToDate(&ArticleTable.s, new(Article))
	parse.AssertUpToDate(&CategoryView.s, new(Category))
}
